### ISSUE TITLE
Actual Drill Upgrade Cost Is Wrong

### ISSUE THREAD

**Issue by yejingyu** [TheClickingGameDev/Towidle#1]
https://github.com/TheClickingGameDev/Towidle/blob/cc1ebf5b12c43e16f6d369a8936eb356f306cc33/Towidle/Scripts/shop.gd#L24
Upgradig drill should cost the Global.drill_upgrade_cost

**Comment by TheClickingGameDev** [comment]
Thank you! I fixed the bug.
